### ISSUE TITLE
你好，关于QQHealthView.java

### ISSUE THREAD

**Issue by DearZack** [burgessjp/MaterialDesignDemo#2]
我尝试着按你的思路也写了一边，但是有点小问题。
在最后的onTouchEvent里，我点击了一下，但是会Toast四下，不知道是为什么，我没用你的那个snackBar

**Comment by burgessjp** [comment]
刚看了下，确实有你说的这个问题。在那里return false就可以了。我之前也没注意，很感谢你的提出。

**Comment by burgessjp** [comment]
刚看了下，确实有你说的这个问题。在那里return false就可以了。我之前也没注意，很感谢你的提出。

**Comment by DearZack** [comment]
这是为什么啊？？
我查了一下在onTouchEvent中，返回true表示消费了这次事件，返回false表示未消费。
按理不是应该消费了就不再次执行了吗？
我抓了下日志，是if那句判断执行了四次，有时候是五次，好不可思议啊

**Comment by burgessjp** [comment]
这是事件消费与传递的知识点，如果不清楚可以再回去看看。返回false就是本次的事件序列，后面的MOVE和UP都不由这个View处理了，然而返回true就是代表这个View会消费掉整个的事件序列后面的MOVE和UP都会由这个View来处理，你知道的只要你的手指没离开这个View MOVE会一直执行。这也就是会出现多次的原因。

**Comment by DearZack** [comment]
谢谢你
