### ISSUE TITLE
做换肤功能添加这个https://github.com/burgessjp/ThemeSkinning类库吗

### ISSUE THREAD

**Issue by tianshaokai** [burgessjp/MaterialDesignDemo#6]
这个库还维护更新吗

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/20695495/6ce87a1a-b627-11e6-91be-2893dc799253.png)
看加载皮肤是加载的这两个文件，这个文件后缀名好特殊，是怎么生成的呢

**Comment by burgessjp** [comment]
关于皮肤文件的生成那篇文章里有详细的介绍，换肤的话可以使用这个库：[ThemeSkinning](https://github.com/burgessjp/ThemeSkinning)，这个库是在维护更新的
