### ISSUE TITLE
换肤后 SnackBar 的颜色没有变

### ISSUE THREAD

**Issue by tianshaokai** [burgessjp/MaterialDesignDemo#7]
![image](https://cloud.githubusercontent.com/assets/6706496/20699319/a4a1ff02-b641-11e6-969f-dcff0f2b6972.png)

**Comment by burgessjp** [comment]
SnackBar是不参与换肤的

**Comment by tianshaokai** [comment]
不参与换肤，就会发现好难看啊

**Comment by tianshaokai** [comment]
SnackBar 也想换肤怎么做呢？？
